### ISSUE TITLE
ArgumentOutOfRangeException: Path variable invalid input causes crash

### ISSUE THREAD

**Issue by Kaitou-3D** [mushroom-guy/mwb-materials#3]
If a user doesn't select a proper path, the application will exception. Hitting continue with the exception dialogue box will result in the application hard locking.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at mwb_materials.MwbMats.BatchExporter.<GenerateInFolder>d__1.MoveNext() in F:\source\git\mwb-materials\mwb-materials\MwbMats\BatchExporter.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at mwb_materials.MwbMats.BatchExporter.<StartBatch>d__2.MoveNext() in F:\source\git\mwb-materials\mwb-materials\MwbMats\BatchExporter.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at mwb_materials.Form1.<FolderButton_Click>d__1.MoveNext() in F:\source\git\mwb-materials\mwb-materials\Form1.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

**Comment by Kaitou-3D** [comment]
Finer Triage:
```csharp
            if (props.VmtRootPath != string.Empty)
            {
                vmtPath = vmtPath.Substring(vmtPath.IndexOf("materials"));
```
If this fails, bad things happen.
